name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          default: true
          override: true
          components: clippy, rustfmt

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Check formatting
        run: cargo fmt  -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --tests --all-features -- -Dclippy::all

      - name: Build
        run: cargo build --all-features --all --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Build nrf52840 examples
        run: |
          cd examples/nrf52840
          cargo build --release

      - name: Build rp2040 examples
        run: |
          cd examples/rp
          cargo build --release

      - name: Build stm32l0 examples
        run: |
          cd examples/stm32l0
          cargo build --release

      - name: Build stm32wl examples
        run: |
          cd examples/stm32wl
          cargo build --release
